#!/usr/bin/env bash

declare path_log=${XDG_CONFIG_HOME:-~/.config}/dot/log
declare path_brightness=$path_log/brightness
declare path_gamma=$path_log/gamma
declare path_monitor=$path_log/monitor

if [[ ! -d $path_log ]];then
    mkdir -p $path_log
fi

if [[ ! -f $path_brightness || "$(cat $path_brightness)" == "" ]];then
    echo "1" > $path_brightness
fi

if [[ ! -f $path_gamma || "$(cat $path_gamma)" == "" ]];then
    echo "1:1:1" > $path_gamma
fi

if [[ ! -f $path_output || "$(cat $path_output)" == "" ]];then
    xrandr --listmonitors | awk '{ if (NR!=1) print $NF }' > $path_monitor
fi
