#!/usr/bin/env bash

if [[ -z "$1" ]];then
    echo "a tu casa pollo"
    exit 1
fi

update() {
    source ~/.config/dot/script/checklog
    declare gamma
    declare brightness
    gamma="$(cat $path_gamma)"
    brightness="$(cat $path_brightness)"
    while IFS= read -r line; do
        xrandr --output "$line" --gamma "$gamma" --brightness "$brightness"
    done < "$path_monitor"
}

case "$1" in
    plus) operation="+";;
    minus) operation="-";;
    update)
        update
        exit
    ;;
    *) echo "a tu casa pollo"; exit 1;;
esac

source ~/.config/dot/script/checklog

calc() {
    awk 'BEGIN { printf "%.2f", '"$*"'; exit }'
}

declare gamma
declare old_brightness
declare new_brightness
declare step="0.2"

gamma="$(cat $path_gamma)"
old_brightness="$(cat $path_brightness)"
new_brightness="$(calc "$old_brightness $operation $step")"

if $(echo "$new_brightness" | awk '{exit !($1 <= 1 && $1 >= 0.2)}');then
    echo $new_brightness > $path_brightness
    while IFS= read -r line; do
        xrandr --output "$line" --gamma "$gamma" --brightness "$new_brightness"
    done < "$path_monitor"
fi

