#!/usr/bin/env bash

ln -s $HOME/.config/dot/i3wm           $HOME/.config/i3              
ln -s $HOME/.config/dot/i3status       $HOME/.config/i3status        
ln -s $HOME/.config/dot/vim            $HOME/.config/vim             
ln -s $HOME/.config/dot/user-dirs.dirs $HOME/.config/user-dirs.dirs  
ln -s $HOME/.config/dot/mimeapps.list  $HOME/.config/mimeapps.list   

# script

ln -s $HOME/.config/dot/script/b           $HOME/.config/i3              
