#!/usr/bin/env bash

filter='#{==:#{pane_start_command},tmux-filetree}'
filetree_index="$(tmux list-panes -F '#{pane_index}' -f "$filter")"
current_index="$(tmux list-panes -F '#{pane_index}' -f "#{pane_active}")"

[[ -z "$filetree_index" ]] && (
    tmux split-window -h -l 20 -t 1 -b 'tmux-filetree'
    tmux select-pane -t "$(( current_index + 1 ))"
) || (
    tmux kill-pane -t 1
    tmux select-pane -t "$(( current_index - 1 ))"
)

