#!/usr/bin/env bash

declare manual
manual="$(apropos . | fzf)"
manual="${manual%% *}"
if [[ -n "$manual" ]];then
    vim -c "runtime ftplugin/man.vim"\
        -c "set filetype=man"\
        -c "Man $manual"\
        -c "only"
fi

