#!/usr/bin/env bash

declare manual_line
declare manual
manual_line="$(apropos . | awk '{print $1}' | fzf)"
command_name="${manual_line%% *}"
if [[ -n "$command_name" ]];then
    tmux new-window man "$command_name"
    # vim -c "runtime ftplugin/man.vim"\
    #     -c "set filetype=man"\
    #     -c "Man $command_name"\
    #     -c "only"
fi

# mensaje de advertencia y error
# export MANPAGER="vim"

# el formato no es le más apropiado para leer los titulos
# se debe limpiar
# export MANPAGER="vim -"

# no usa vim
# export MANPAGER="sh -c 'col -bx | bat --language man --plain'"

# no funciona
# export MANPAGER="col -b -x | view -c 'set filetype=man nomodified nolist' -"

# mensaje de advertencia y error
# export MANPAGER="sh -c 'col -b -x | vim'"
# export MANPAGER="man $1"

# https://stackoverflow.com/a/16740302

