#!/usr/bin/env bash

list_monitors() {
    xrandr --listmonitors | awk '{ if (NR!=1) print $NF }'
}

main() {
    local mode="$1"
    local gamma
    local brightness
    case "$mode" in
        nigth)
            gamma="1.1:0.8:0.7"
            brightness="0.5"
        ;;
        ligth)
            gamma="1:1:1"
            brightness="0.9"
        ;;
        *)
            echo "error: invalid option"
            exit 1
        ;;
    esac
    local -a monitors=($(list_monitors))
    for item in "${monitors[@]}";do
        echo "$item"
        xrandr --output "$item" --gamma "$gamma" --brightness "$brightness"
    done
}

main "$@"

