#!/usr/bin/env bash

declare -r path="$HOME/w/b"

clipboard() {
    local clipboard
    clipboard="$(xclip -selection clipboard -out)"
    echo "$clipboard"
}

select_file() {
    local files
    files="$(ls -1 "$path" | dmenu -l 10)"
    echo "$files"
}

select_url() {
    local url
    local file="$1"
    if [[ -n "$file" ]];then
        # select from file
        url="$(cat "$path/$file" | dmenu -l 10)"
    else
        # select from directory
        url="$(grep --no-filename "^http" "$path"/* | dmenu -l 10)"
    fi
    echo "$url"
}

open() {
    local url="$1"
    if [[ -n "$url" ]];then
        xdg-open "${url%% *}" &> /dev/null &
        if (( $? == 0 ));then
            disown
        fi
    fi
}

rm_url() {
    local file="$1"
    local url="$2"
    while read -r line;do
        if [[ "$line" != "$url" ]];then
            echo "$line"
        fi
    done < "$path"/"$file" > tmp
    mv tmp "$path"/"$file"
}

save() {
    local file
    local text
    file="$(select_file)"
    text="$(clipboard)"
    if [[ "$text" != http* ]];then
        return 1
    fi
    echo "$text" >> "$path"/"$file"
}

open_url() {
    local url
    url="$(select_url)"
    open "$url"
}

open_url_from_file() {
    local url
    local file
    file="$(select_file)"
    url="$(select_url "$file")"
    open "$url"
}

remove_url_from_file() {
    local url
    local file
    file="$(select_file)"
    url="$(select_url "$file")"
    rm_url "$file" "$url"
}

main() {
    local url
    local file
    local action="$1"
    case "$action" in
        save) save ;;
        open) open_url ;;
        open-file) open_url_from_file ;;
        rm) remove_url_from_file ;;
    esac
}

main "$@"

