#!/usr/bin/env bash

declare -r path="$HOME/w/b"

clipboard() {
    local clipboard
    clipboard="$(xclip -selection clipboard -out)"
    echo "$clipboard"
}

write_in_file() {
    local text
    text="$(clipboard)"
    if [[ "$text" == http* ]];then
        echo "$text" >> $path
    fi
}

select_file() {
    local files
    files="$(ls -1 "$path" | dmenu -l 10)"
    echo "$files"
}

select_url_from_file() {
    local url
    local file="$1"
    url="$(cat "$path/$file" | dmenu -l 10)"
    echo "$url"
}

select_url_from_directory() {
    local url
    url="$(grep --no-filename "^http" "$path"/* | dmenu -l 10)"
    echo "$url"
}

select_url() {
    local url
    local file="$1"
    if [[ -n "$file" ]];then
        url="$(select_url_from_file "$file")"
    else
        url="$(select_url_from_directory)"
    fi
    echo "$url"
}

open() {
    local url="$1"
    if [[ -n "$url" ]];then
        xdg-open "${url%% *}" &> /dev/null &
        if (( $? == 0 ));then
            disown
        fi
    fi
}
open_from_file() {
    local url
    local file="$1"
    if [[ -n "$file" ]];then
        url="$(select_url "$file")"
        open "$url"
    fi
    echo "$url"
}

main() {
    local url
    local file
    local action="$1"
    case "$action" in
        save)
            write_in_file
            ;;
        open)
            url="$(select_url)"
            open "$url"
            ;;
        open-file)
            file="$(select_file)"
            open_from_file "$file"
            ;;
    esac
}

main "$@"

