#!/usr/bin/env bash

declare -r path="$HOME/w/b"

clipboard() {
    local clipboard
    clipboard="$(xclip -selection clipboard -out)"
    echo "$clipboard"
}

select_file() {
    local files
    files="$(ls -1 "$path" | dmenu -l 10)"
    echo "$files"
}

select_url_from_file() {
    local url
    local file="$1"
    url="$(cat "$path/$file" | dmenu -l 10)"
    echo "$url"
}

select_url_from_directory() {
    local url
    url="$(grep --no-filename "^http" "$path"/* | dmenu -l 10)"
    echo "$url"
}

select_url() {
    local url
    local file="$1"
    if [[ -n "$file" ]];then
        url="$(select_url_from_file "$file")"
    else
        url="$(select_url_from_directory)"
    fi
    echo "$url"
}

open() {
    local url="$1"
    if [[ -n "$url" ]];then
        xdg-open "${url%% *}" &> /dev/null &
        if (( $? == 0 ));then
            disown
        fi
    fi
}

open_from_file() {
    local url
    local file="$1"
    if [[ ! -r "$path"/"$file" ]];then
        echo "error (1): file '$file' doesn't exist or cannot be read"
        return 1
    fi
    url="$(select_url "$file")"
    open "$url"
}

rm_url() {
    local file="$1"
    local url="$2"
    if [[ "$url" != http* ]];then
        return 1
    fi
    while read -r line;do
        if [[ "$line" != "$url" ]];then
            echo "$line"
        fi
    done < "$path"/"$file" > tmp
    mv tmp "$path"/"$file"
}

save() {
    local file
    local text
    file="$(select_file)"
    text="$(clipboard)"
    if [[ "$text" != http* ]];then
        return 1
    fi
    echo "$text" >> "$path"/"$file"
}

main() {
    local url
    local file
    local action="$1"
    case "$action" in
        save) save ;;
        open)
            url="$(select_url)"
            open "$url"
            ;;
        open-file)
            file="$(select_file)"
            open_from_file "$file"
            ;;
        rm)
            file="$(select_file)"
            url="$(select_url "$file")"
            rm_url "$file" "$url"
            ;;
    esac
}

main "$@"

