#!/usr/bin/env bash
declare -r fmt='#{session_id}:|#S|(#{session_attached} attached)'
{ tmux display-message -p -F "$fmt" && tmux list-sessions -F "$fmt"; }\
| awk '!seen[$1]++'\
| column -t -s'|'\
| fzf --bind ctrl-space:accept -q '$' --reverse --prompt 'switch session: ' -1\
| cut -d':' -f1\
| xargs tmux switch-client -t 2> /dev/null
